/* tslint:disable */
/* eslint-disable */
/**
 * Vector Tile Lab API
 * API for Vector Tile Lab
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDatasetsTilesets400Response
 */
export interface CreateDatasetsTilesets400Response {
    /**
     * 
     * @type {string}
     * @memberof CreateDatasetsTilesets400Response
     */
    error?: string;
}

/**
 * Check if a given object implements the CreateDatasetsTilesets400Response interface.
 */
export function instanceOfCreateDatasetsTilesets400Response(value: object): value is CreateDatasetsTilesets400Response {
    return true;
}

export function CreateDatasetsTilesets400ResponseFromJSON(json: any): CreateDatasetsTilesets400Response {
    return CreateDatasetsTilesets400ResponseFromJSONTyped(json, false);
}

export function CreateDatasetsTilesets400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDatasetsTilesets400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function CreateDatasetsTilesets400ResponseToJSON(json: any): CreateDatasetsTilesets400Response {
    return CreateDatasetsTilesets400ResponseToJSONTyped(json, false);
}

export function CreateDatasetsTilesets400ResponseToJSONTyped(value?: CreateDatasetsTilesets400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

