/* tslint:disable */
/* eslint-disable */
/**
 * Vector Tile Lab API
 * API for Vector Tile Lab
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDatasetsTilesetsRequest
 */
export interface CreateDatasetsTilesetsRequest {
    /**
     * Name for the new tileset
     * @type {string}
     * @memberof CreateDatasetsTilesetsRequest
     */
    name: string;
    /**
     * Maximum zoom level (0-22 or 'g' for guess)
     * @type {string}
     * @memberof CreateDatasetsTilesetsRequest
     */
    maxZoom?: string;
    /**
     * Whether to drop densest as needed
     * @type {boolean}
     * @memberof CreateDatasetsTilesetsRequest
     */
    dropDensest?: boolean;
}

/**
 * Check if a given object implements the CreateDatasetsTilesetsRequest interface.
 */
export function instanceOfCreateDatasetsTilesetsRequest(value: object): value is CreateDatasetsTilesetsRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateDatasetsTilesetsRequestFromJSON(json: any): CreateDatasetsTilesetsRequest {
    return CreateDatasetsTilesetsRequestFromJSONTyped(json, false);
}

export function CreateDatasetsTilesetsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDatasetsTilesetsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'maxZoom': json['max_zoom'] == null ? undefined : json['max_zoom'],
        'dropDensest': json['drop_densest'] == null ? undefined : json['drop_densest'],
    };
}

export function CreateDatasetsTilesetsRequestToJSON(value?: CreateDatasetsTilesetsRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'max_zoom': value['maxZoom'],
        'drop_densest': value['dropDensest'],
    };
}

