/* tslint:disable */
/* eslint-disable */
/**
 * Vector Tile Lab API
 * API for Vector Tile Lab
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListDatasetsTiers404Response
 */
export interface ListDatasetsTiers404Response {
    /**
     * 
     * @type {string}
     * @memberof ListDatasetsTiers404Response
     */
    error?: string;
}

/**
 * Check if a given object implements the ListDatasetsTiers404Response interface.
 */
export function instanceOfListDatasetsTiers404Response(value: object): value is ListDatasetsTiers404Response {
    return true;
}

export function ListDatasetsTiers404ResponseFromJSON(json: any): ListDatasetsTiers404Response {
    return ListDatasetsTiers404ResponseFromJSONTyped(json, false);
}

export function ListDatasetsTiers404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListDatasetsTiers404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function ListDatasetsTiers404ResponseToJSON(json: any): ListDatasetsTiers404Response {
    return ListDatasetsTiers404ResponseToJSONTyped(json, false);
}

export function ListDatasetsTiers404ResponseToJSONTyped(value?: ListDatasetsTiers404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

