/* tslint:disable */
/* eslint-disable */
/**
 * Vector Tile Lab API
 * API for Vector Tile Lab
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `quantile` - QUANTILE
 * * `natural_breaks` - NATURAL_BREAKS
 * * `percentile` - PERCENTILE
 * @export
 */
export const MethodEnum = {
    Quantile: 'quantile',
    NaturalBreaks: 'natural_breaks',
    Percentile: 'percentile'
} as const;
export type MethodEnum = typeof MethodEnum[keyof typeof MethodEnum];


export function instanceOfMethodEnum(value: any): boolean {
    for (const key in MethodEnum) {
        if (Object.prototype.hasOwnProperty.call(MethodEnum, key)) {
            if (MethodEnum[key as keyof typeof MethodEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MethodEnumFromJSON(json: any): MethodEnum {
    return MethodEnumFromJSONTyped(json, false);
}

export function MethodEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): MethodEnum {
    return json as MethodEnum;
}

export function MethodEnumToJSON(value?: MethodEnum | null): any {
    return value as any;
}

export function MethodEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): MethodEnum {
    return value as MethodEnum;
}

