/* tslint:disable */
/* eslint-disable */
/**
 * Vector Tile Lab API
 * API for Vector Tile Lab
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RetrieveDatasetsTilesetsPresignedUrl200Response
 */
export interface RetrieveDatasetsTilesetsPresignedUrl200Response {
    /**
     * 
     * @type {string}
     * @memberof RetrieveDatasetsTilesetsPresignedUrl200Response
     */
    presignedUrl: string;
    /**
     * URL expiration time in seconds
     * @type {number}
     * @memberof RetrieveDatasetsTilesetsPresignedUrl200Response
     */
    expiresIn: number;
}

/**
 * Check if a given object implements the RetrieveDatasetsTilesetsPresignedUrl200Response interface.
 */
export function instanceOfRetrieveDatasetsTilesetsPresignedUrl200Response(value: object): value is RetrieveDatasetsTilesetsPresignedUrl200Response {
    if (!('presignedUrl' in value) || value['presignedUrl'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    return true;
}

export function RetrieveDatasetsTilesetsPresignedUrl200ResponseFromJSON(json: any): RetrieveDatasetsTilesetsPresignedUrl200Response {
    return RetrieveDatasetsTilesetsPresignedUrl200ResponseFromJSONTyped(json, false);
}

export function RetrieveDatasetsTilesetsPresignedUrl200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetrieveDatasetsTilesetsPresignedUrl200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'presignedUrl': json['presigned_url'],
        'expiresIn': json['expires_in'],
    };
}

export function RetrieveDatasetsTilesetsPresignedUrl200ResponseToJSON(value?: RetrieveDatasetsTilesetsPresignedUrl200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'presigned_url': value['presignedUrl'],
        'expires_in': value['expiresIn'],
    };
}

