/* tslint:disable */
/* eslint-disable */
/**
 * Vector Tile Lab API
 * API for Vector Tile Lab
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RetrieveDatasetsProgress500Response
 */
export interface RetrieveDatasetsProgress500Response {
    /**
     * 
     * @type {string}
     * @memberof RetrieveDatasetsProgress500Response
     */
    error?: string;
}

/**
 * Check if a given object implements the RetrieveDatasetsProgress500Response interface.
 */
export function instanceOfRetrieveDatasetsProgress500Response(value: object): value is RetrieveDatasetsProgress500Response {
    return true;
}

export function RetrieveDatasetsProgress500ResponseFromJSON(json: any): RetrieveDatasetsProgress500Response {
    return RetrieveDatasetsProgress500ResponseFromJSONTyped(json, false);
}

export function RetrieveDatasetsProgress500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetrieveDatasetsProgress500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function RetrieveDatasetsProgress500ResponseToJSON(value?: RetrieveDatasetsProgress500Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'error': value['error'],
    };
}

