/* tslint:disable */
/* eslint-disable */
/**
 * Vector Tile Lab API
 * API for Vector Tile Lab
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RetrieveDatasetsProgress200Response
 */
export interface RetrieveDatasetsProgress200Response {
    /**
     * 
     * @type {number}
     * @memberof RetrieveDatasetsProgress200Response
     */
    datasetId: number;
    /**
     * 
     * @type {string}
     * @memberof RetrieveDatasetsProgress200Response
     */
    datasetName: string;
    /**
     * 
     * @type {number}
     * @memberof RetrieveDatasetsProgress200Response
     */
    progress: number;
    /**
     * 
     * @type {string}
     * @memberof RetrieveDatasetsProgress200Response
     */
    status: RetrieveDatasetsProgress200ResponseStatusEnum;
}


/**
 * @export
 */
export const RetrieveDatasetsProgress200ResponseStatusEnum = {
    InProgress: 'in_progress',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type RetrieveDatasetsProgress200ResponseStatusEnum = typeof RetrieveDatasetsProgress200ResponseStatusEnum[keyof typeof RetrieveDatasetsProgress200ResponseStatusEnum];


/**
 * Check if a given object implements the RetrieveDatasetsProgress200Response interface.
 */
export function instanceOfRetrieveDatasetsProgress200Response(value: object): value is RetrieveDatasetsProgress200Response {
    if (!('datasetId' in value) || value['datasetId'] === undefined) return false;
    if (!('datasetName' in value) || value['datasetName'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function RetrieveDatasetsProgress200ResponseFromJSON(json: any): RetrieveDatasetsProgress200Response {
    return RetrieveDatasetsProgress200ResponseFromJSONTyped(json, false);
}

export function RetrieveDatasetsProgress200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetrieveDatasetsProgress200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'datasetId': json['dataset_id'],
        'datasetName': json['dataset_name'],
        'progress': json['progress'],
        'status': json['status'],
    };
}

export function RetrieveDatasetsProgress200ResponseToJSON(value?: RetrieveDatasetsProgress200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'dataset_id': value['datasetId'],
        'dataset_name': value['datasetName'],
        'progress': value['progress'],
        'status': value['status'],
    };
}

