/* tslint:disable */
/* eslint-disable */
/**
 * Vector Tile Lab API
 * API for Vector Tile Lab
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RetrieveDatasetsTilesetsPresignedUrl404Response
 */
export interface RetrieveDatasetsTilesetsPresignedUrl404Response {
    /**
     * 
     * @type {string}
     * @memberof RetrieveDatasetsTilesetsPresignedUrl404Response
     */
    error?: string;
}

/**
 * Check if a given object implements the RetrieveDatasetsTilesetsPresignedUrl404Response interface.
 */
export function instanceOfRetrieveDatasetsTilesetsPresignedUrl404Response(value: object): value is RetrieveDatasetsTilesetsPresignedUrl404Response {
    return true;
}

export function RetrieveDatasetsTilesetsPresignedUrl404ResponseFromJSON(json: any): RetrieveDatasetsTilesetsPresignedUrl404Response {
    return RetrieveDatasetsTilesetsPresignedUrl404ResponseFromJSONTyped(json, false);
}

export function RetrieveDatasetsTilesetsPresignedUrl404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetrieveDatasetsTilesetsPresignedUrl404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function RetrieveDatasetsTilesetsPresignedUrl404ResponseToJSON(value?: RetrieveDatasetsTilesetsPresignedUrl404Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'error': value['error'],
    };
}

