/* tslint:disable */
/* eslint-disable */
/**
 * Vector Tile Lab API
 * API for Vector Tile Lab
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RetrieveDatasetsTilesetsProgress200Response
 */
export interface RetrieveDatasetsTilesetsProgress200Response {
    /**
     * 
     * @type {number}
     * @memberof RetrieveDatasetsTilesetsProgress200Response
     */
    tilesetId: number;
    /**
     * 
     * @type {string}
     * @memberof RetrieveDatasetsTilesetsProgress200Response
     */
    tilesetName: string;
    /**
     * 
     * @type {number}
     * @memberof RetrieveDatasetsTilesetsProgress200Response
     */
    progress: number;
    /**
     * 
     * @type {string}
     * @memberof RetrieveDatasetsTilesetsProgress200Response
     */
    status: RetrieveDatasetsTilesetsProgress200ResponseStatusEnum;
}


/**
 * @export
 */
export const RetrieveDatasetsTilesetsProgress200ResponseStatusEnum = {
    InProgress: 'in_progress',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type RetrieveDatasetsTilesetsProgress200ResponseStatusEnum = typeof RetrieveDatasetsTilesetsProgress200ResponseStatusEnum[keyof typeof RetrieveDatasetsTilesetsProgress200ResponseStatusEnum];


/**
 * Check if a given object implements the RetrieveDatasetsTilesetsProgress200Response interface.
 */
export function instanceOfRetrieveDatasetsTilesetsProgress200Response(value: object): value is RetrieveDatasetsTilesetsProgress200Response {
    if (!('tilesetId' in value) || value['tilesetId'] === undefined) return false;
    if (!('tilesetName' in value) || value['tilesetName'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function RetrieveDatasetsTilesetsProgress200ResponseFromJSON(json: any): RetrieveDatasetsTilesetsProgress200Response {
    return RetrieveDatasetsTilesetsProgress200ResponseFromJSONTyped(json, false);
}

export function RetrieveDatasetsTilesetsProgress200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetrieveDatasetsTilesetsProgress200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'tilesetId': json['tileset_id'],
        'tilesetName': json['tileset_name'],
        'progress': json['progress'],
        'status': json['status'],
    };
}

export function RetrieveDatasetsTilesetsProgress200ResponseToJSON(json: any): RetrieveDatasetsTilesetsProgress200Response {
    return RetrieveDatasetsTilesetsProgress200ResponseToJSONTyped(json, false);
}

export function RetrieveDatasetsTilesetsProgress200ResponseToJSONTyped(value?: RetrieveDatasetsTilesetsProgress200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tileset_id': value['tilesetId'],
        'tileset_name': value['tilesetName'],
        'progress': value['progress'],
        'status': value['status'],
    };
}

