openapi: 3.0.3
info:
  title: Vector Tile Lab API
  version: 1.0.0
  description: API for Vector Tile Lab
paths:
  /api/v1/datasets/:
    get:
      operationId: listDatasets
      tags:
      - datasets
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dataset'
          description: ''
    post:
      operationId: createDatasets
      tags:
      - datasets
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                geojson_file:
                  type: string
                  format: binary
                shp_file:
                  type: string
                  format: binary
                shx_file:
                  type: string
                  format: binary
                dbf_file:
                  type: string
                  format: binary
                prj_file:
                  type: string
                  format: binary
                cpg_file:
                  type: string
                  format: binary
              required:
              - name
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
          description: ''
  /api/v1/datasets/{datasetId}/tilesets/:
    get:
      operationId: listDatasetsTilesets
      parameters:
      - in: path
        name: datasetId
        schema:
          type: integer
        required: true
      - in: query
        name: status
        schema:
          type: string
          enum:
          - completed
          - failed
          - in_progress
        description: |-
          * `in_progress` - IN_PROGRESS
          * `completed` - COMPLETED
          * `failed` - FAILED
      tags:
      - datasets
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tileset'
          description: ''
    post:
      operationId: createDatasetsTilesets
      description: Create a new tileset with custom tippecanoe options.
      parameters:
      - in: path
        name: datasetId
        schema:
          type: integer
        required: true
      tags:
      - datasets
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name for the new tileset
                max_zoom:
                  type: string
                  description: Maximum zoom level (0-22 or 'g' for guess)
                  default: g
                drop_densest:
                  type: boolean
                  description: Whether to drop densest as needed
                  default: true
              required:
              - name
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tileset'
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
          description: ''
        '404':
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
          description: ''
  /api/v1/datasets/{datasetId}/tilesets/{id}/:
    get:
      operationId: retrieveDatasetsTilesets
      parameters:
      - in: path
        name: datasetId
        schema:
          type: integer
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - datasets
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tileset'
          description: ''
    delete:
      operationId: destroyDatasetsTilesets
      parameters:
      - in: path
        name: datasetId
        schema:
          type: integer
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - datasets
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/v1/datasets/{datasetId}/tilesets/{id}/presigned_url/:
    get:
      operationId: retrieveDatasetsTilesetsPresignedUrl
      description: Generate a presigned URL to access the PMTiles file directly from
        MinIO/S3 storage.
      summary: Get presigned URL for PMTiles file
      parameters:
      - in: path
        name: datasetId
        schema:
          type: integer
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - datasets
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  presigned_url:
                    type: string
                    format: uri
                  expires_in:
                    type: integer
                    description: URL expiration time in seconds
                required:
                - presigned_url
                - expires_in
          description: ''
        '404':
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
          description: ''
        '500':
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
          description: ''
  /api/v1/datasets/{datasetId}/tilesets/{id}/progress/:
    get:
      operationId: retrieveDatasetsTilesetsProgress
      description: Retrieves the current generation progress for a specific tileset
        from Redis cache.
      summary: Get tileset generation progress
      parameters:
      - in: path
        name: datasetId
        schema:
          type: integer
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - datasets
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  tileset_id:
                    type: integer
                  tileset_name:
                    type: string
                  progress:
                    type: integer
                    minimum: 0
                    maximum: 100
                  status:
                    type: string
                    enum:
                    - in_progress
                    - completed
                    - failed
                required:
                - tileset_id
                - tileset_name
                - progress
                - status
          description: ''
        '500':
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
          description: ''
  /api/v1/datasets/{id}/:
    get:
      operationId: retrieveDatasets
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this dataset.
        required: true
      tags:
      - datasets
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
          description: ''
    delete:
      operationId: destroyDatasets
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this dataset.
        required: true
      tags:
      - datasets
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/v1/datasets/{id}/progress/:
    get:
      operationId: retrieveDatasetsProgress
      description: Retrieves the current processing progress for a specific dataset
        from Redis cache.
      summary: Get dataset processing progress
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this dataset.
        required: true
      tags:
      - datasets
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  dataset_id:
                    type: integer
                  dataset_name:
                    type: string
                  progress:
                    type: integer
                    minimum: 0
                    maximum: 100
                  status:
                    type: string
                    enum:
                    - in_progress
                    - completed
                    - failed
                required:
                - dataset_id
                - dataset_name
                - progress
                - status
          description: ''
        '500':
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
          description: ''
components:
  schemas:
    Dataset:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        geojson_file:
          type: string
          format: uri
          nullable: true
        shp_file:
          type: string
          format: uri
          nullable: true
        shx_file:
          type: string
          format: uri
          nullable: true
        dbf_file:
          type: string
          format: uri
          nullable: true
        prj_file:
          type: string
          format: uri
          nullable: true
        cpg_file:
          type: string
          format: uri
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - id
      - name
      - updated_at
    StatusEnum:
      enum:
      - in_progress
      - completed
      - failed
      type: string
      description: |-
        * `in_progress` - IN_PROGRESS
        * `completed` - COMPLETED
        * `failed` - FAILED
    Tileset:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        dataset:
          type: integer
          readOnly: true
        dataset_name:
          type: string
          readOnly: true
        name:
          type: string
          readOnly: true
        pmtiles_file:
          type: string
          format: uri
          readOnly: true
        status:
          allOf:
          - $ref: '#/components/schemas/StatusEnum'
          readOnly: true
        metadata:
          readOnly: true
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - dataset
      - dataset_name
      - id
      - metadata
      - name
      - pmtiles_file
      - status
      - updated_at
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
