# Generated by Django 5.2.6 on 2025-09-30 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("geojson_file", models.FileField(upload_to="datasets/geojson/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tileset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("pmtiles_file", models.FileField(upload_to="datasets/pmtiles/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "IN_PROGRESS"),
                            ("completed", "COMPLETED"),
                            ("failed", "FAILED"),
                        ],
                        default="in_progress",
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tilesets",
                        to="lab.dataset",
                    ),
                ),
            ],
        ),
    ]
