# Generated by Django 5.2.6 on 2025-10-23 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lab", "0002_dataset_cpg_file_dataset_dbf_file_dataset_prj_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TierList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.CharField(max_length=255)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("quantile", "QUANTILE"),
                            ("natural_breaks", "NATURAL_BREAKS"),
                        ],
                        default="quantile",
                        max_length=50,
                    ),
                ),
                ("breaks", models.JSONField()),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier_lists",
                        to="lab.dataset",
                    ),
                ),
            ],
            options={
                "unique_together": {("dataset", "field", "method")},
            },
        ),
    ]
