# Generated by Django 5.2.6 on 2026-01-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lab", "0003_tierlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tierlist",
            name="method",
            field=models.CharField(
                choices=[
                    ("quantile", "QUANTILE"),
                    ("natural_breaks", "NATURAL_BREAKS"),
                    ("percentile", "PERCENTILE"),
                ],
                default="quantile",
                max_length=50,
            ),
        ),
    ]
